### ISSUE TITLE
Not working out of box

### ISSUE THREAD

**Issue by ghost** [ansemjo/angular2-pdf417-barcode#1]
Hi,

I am not expert.
This library does not seem to be working out of the box.

Here some more observations:

```
import { PDF417BarcodeModule } from 'pdf417-module';
...

@NgModule({
  exports: [
    CommonModule,
    FormsModule,
    PDF417BarcodeModule,
  ]
}) export class SharedModule { }

```
1.) Why are we EXPORTING ? Should this not be an import?
2) The PDF417BarcodeModule is not found for import

```
<pdf417barcode [text]="'Hello, World!'" [opts]="{ pxw: 2, pxh: 2 }"></pdf417barcode>
```
When we do [text] the system is expecting a variable. So how come we are giving it a string.

Thanks in advance.
TeaCii

**Comment by ansemjo** [comment]
I export in the example because the example uses a shared module `SharedModule`. That shared module is then imported in the module `OrderFormModule` which uses the barcode in its component templates:

```typescript
import { SharedModule } from '../shared-module';
...
@NgModule({
  imports:      [ SharedModule, OrderFormRouting ],
  declarations: [ OrderFormComponent, OrderFieldComponent ]
})
export class OrderFormModule { }
```

Of couse, you could directly import it in your module:

```typescript
import { SharedModule } from '../shared-module';
import { PDF417BarcodeModule } from 'pdf417-module';
...
@NgModule({
  imports:      [ PDF417BarcodeModule, SharedModule, OrderFormRouting ],  /* <----- */
  declarations: [ OrderFormComponent, OrderFieldComponent ]
})
export class OrderFormModule { }
```
That way, the directive should work.

Using square bracket notation expects a valid **expression**. A local string variable would be a valid expression, as is a string literal. For demo purposes I used a string literal, as can be seen by the single quotation marks: `[text]="'Hello, World!'"`. For anything more than a test you would probably use: `[text]="myStringVar"`, while you have `public myStringVar: string = 'Hello World!';` somewhere in your component class.

I hope that helps.
I'll close this for now, feel free to get back to me if it still does not work.
