### ISSUE TITLE
Cannot find name 'require'.

### ISSUE THREAD

**Issue by Midhilaj** [ansemjo/angular2-pdf417-barcode#4]
ERROR in node_modules/angular2-pdf417-barcode/index.ts(3,16): error TS2304: Cannot find name 'require'.

**Comment by ansemjo** [comment]
You probably need to install [`@types/node`](https://www.npmjs.com/package/@types/node) in your project and instruct your Typescript compiler to use those type defintions.

If you're using an `angular-cli` project, it should be enough to install the package. Otherwise [configure](https://www.typescriptlang.org/docs/handbook/compiler-options.html) your `tsconfig.json` appropriately:
```
{
  "compilerOptions": {
    ...
    "typeRoots": [
      "node_modules/@types"
    ],
    ...
  },
  ...
}
```

**Comment by ansemjo** [comment]
I'll assume your problem is fixed and close this issue.

**Comment by ansemjo** [comment]
It might have been a packaging error as well. I've repackaged for Angular 6+ due to #5, so this might have been properly fixed now, too.
